// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbcurbpbqieappaoxoov.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJiY3VyYnBicWllYXBwYW94b292Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDU0NzgsImV4cCI6MjA2Nzc4MTQ3OH0.u8OZW0A2GNopC9I3A-EqcpLBJ8JkmsRoewCWnyVdtU8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});